# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2308ee243556d3e1cc14517dfcb2990148c3ca7c4bb99f41507e10dc01ac6fa636adcb603e672ec7a7a0250875fc335d71ccc7fab9774055919948963d33d7e

test:
  secret_key_base: e4040be495ba2f71b33840cb10a2467086281e89c3e873b00b6f0ccf2baf9649324f33840b120db9bbfb5a4632224ad4490ea7b02404f260b18a33c579601d2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
